mainSections = ["post"]
rssFullContent = true
favicon = "img/favicon.png"

apiBase = ""

githubCommentsRepo = "w2343419-del/Vantalens"
githubCommentsLabelApproved = "approved"
githubCommentsLabelPending = "pending"
githubCommentsLabelComment = "comment"

defaultContentLanguage = "zh-cn"
hasCJKLanguage = true

[article]
readingTime = true
math = true

[colorScheme]
toggle = true
default = "auto"

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"
[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "links"
[widgets.homepage.params]
title = "Links"

[[widgets.homepage.params.items]]
name = "Google"
url = "https://google.com"
desc = "Search Engine"
